### ISSUE TITLE
Unallowed list of producerIds

### ISSUE THREAD

**Issue by ronrlin** [CrowdTangle/API#1]
I'm trying to use the /leaderboard service to pull down data/reporting for a Facebook and Twitter handle using the API.  I'm not having any trouble pulling down the Facebook data, but getting the following error when I try to pull a Twitter handle (accountId= 51719): 
{
  "status": 400,
  "code": 21,
  "message": "Unallowed list of producerIds: 51719"
}

Any idea what this means or why I'm having this problem?

**Comment by mattynoce** [comment]
As discussed offline, the issue was not having this particular account in the dashboard Ron was trying to access. After he added it to the dashboard, the call worked as expected.
