### ISSUE TITLE
Leaderboard for Saved Searches

### ISSUE THREAD

**Issue by allank** [CrowdTangle/API#11]
Hello,

I tried to return the Leaderboard data for a saved search.  The URL in the CrowdTangle web interface updates to show a unique listID when I navigate to the saved search (for example `https://apps.crowdtangle.com/campaignslug/lists/123456`), but when I use `123456` as the `listId` in my params, I get an empty response.  Am I doing something wrong, or is this not currently supported?  If not, is it something that is on the roadmap?

Example params:

```
params = {
    'listId': '123456',
    'count': 50,
}
```

Response:

`{'status': 200, 'result': {'accountStatistics': [], 'pagination': {}}}`

thanks!

**Comment by tkamin** [comment]
Thanks for the suggestion! Unfortunately, I don't believe we support leaderboard data in a saved search right now.
