### ISSUE TITLE
Video views and IGTV

### ISSUE THREAD

**Issue by freeIsa** [CrowdTangle/API#14]
Hello,
I have noticed that, while available at the user interface, the number of views for videos is currently not returned by the API. Is it possible to add this metric to the set of info returned by the API? That would be very useful.

Also, there is some malfunctioning in the "type" filter: it looks like when filtering for "IGTV" in the post requests, one gets all types of posts (including IGTV ones), while with no filter one gets all posts *except* IGTV ones. Is this filter going to be fixed anytime soon?

Thank you all for your work!

**Comment by tkamin** [comment]
Hi, 

We don't have video views in our API per the comment at the bottom here: https://help.crowdtangle.com/en/articles/1189615-facebook-and-instagram-video-views. 

I'm checking on whether the IGTV issue was fixed.

**Comment by tkamin** [comment]
The IGTV issues look fixed!
