### ISSUE TITLE
GET /posts response does not return listIds that posts were retrieved from

### ISSUE THREAD

**Issue by limmabean** [CrowdTangle/API#15]
This is only really an issue when multiple listIds are used or listIds is null (i.e. the entire dashboard). This means that there is some ambiguity from where the post was taken from. As you can see in the example given in the Wiki, The GET /posts response does not include which list or lists the post is retrieved from. The result is that it is impossible to tell which listIds a post is from if multiple listIds or listIds = _null_ is used in the header.
```
"id": 1662400672,
        "platformId": "93625750491_10156590943270492",
        "platform": "Facebook",
        "date": "2016-02-09 15:00:00",
        "updated": "2016-03-01 02:04:41",
        "type": "photo",
        "message": "Happy Birthday to #Phillies Wall of Famer John Kruk!",
        "expandedLinks": [
          {
            "original": "https://www.facebook.com/Phillies/photos/a.188899285491.269976.93625750491/10156590943270492/?type=3",
            "expanded": "https://www.facebook.com/Phillies/photos/a.188899285491.269976.93625750491/10156590943270492/?type=3"
          }
        ],
        "link": "https://www.facebook.com/Phillies/photos/a.188899285491.269976.93625750491/10156590943270492/?type=3",
        "postUrl": "https://www.facebook.com/Phillies/posts/10156590943270492",
        "subscriberCount": 1684347,
        "score": 8.738522954091817,
        "media": [
          {
            "type": "photo",
            "url": "https://scontent.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/p720x720/12728987_10156590943270492_90073343638331316_n.jpg?oh=c7a16bfd8b41e13fdf54e62daa07795c&oe=576AD842",
            "height": 720,
            "width": 720,
            "full": "https://scontent.xx.fbcdn.net/hphotos-xfp1/v/t1.0-9/p720x720/12728987_10156590943270492_90073343638331316_n.jpg?oh=c7a16bfd8b41e13fdf54e62daa07795c&oe=576AD842"
          }
        ],
        "statistics": {
          "actual": {
            "likeCount": 11475,
            "shareCount": 1197,
            "commentCount": 465,
            "loveCount": 0,
            "wowCount": 0,
            "hahaCount": 0,
            "sadCount": 0,
            "angryCount": 0
          },
          "expected": {
            "likeCount": 1966,
            "shareCount": 160,
            "commentCount": 80,
            "loveCount": 0,
            "wowCount": 0,
            "hahaCount": 0,
            "sadCount": 0,
            "angryCount": 0
          }
        },
        "account": {
          "id": 992,
          "name": "Philadelphia Phillies",
          "handle": "Phillies",
          "profileImage": "https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/17554304_10158560861625492_845952810880537491_n.jpg?oh=79c8c102377f9cf19fafada807fcece4&oe=594D229D",
          "subscriberCount": 1703396,
          "url": "https://www.facebook.com/93625750491",
          "platform": "Facebook",
          "platformId": "93625750491",
          "verified": true
        }
      },
```
A method of solving this issue from the API user's perspective is to send several GET /posts requests with only a single listId used in each header. This way there is an assurance from where the post originated from. However, as the number of lists included increases, issues with the number of requests (restrictions on # requests/period) require configuring delays to run. This issue could be solved by providing a source listId in the response with each post. Then the ambiguity would be cleared.

**Comment by mattynoce** [comment]
Hey Matthew. Do you have a specific use case for this? When we execute the query, we smush the lists together (so as to remove duplicate accounts) to send in the filtered set of accounts to find pages within. Since you (as the user) create the lists and know which pages/accounts are in each list, this is not something we ever considered building in.

But it sounds a bit like you're saying that the issue is that you fire off a bunch of requests, and when a response comes back you can't always tell which request it relates to. Is that it? 

Let me know what your particular issue is and we can see where that takes us.

**Comment by limmabean** [comment]
Hi! Thank you for reaching out to this issue. That is not quite the problem we are facing. The issue is that we fire a single /posts request with more than one listID defined and we receive a list of posts. Out of those posts, we can't tell which post came from which list, just which account Id the post came from. It would be very helpful to see which list (or if the account was in two lists, both lists) the post came from.

We did find a solution. We decided to prefetch a list's account ids using the /lists/:listId/accounts endpoint and storing those values to be compared to a fetched post's account id when it is found using the /posts endpoint. **The rather unique use case is that we do not have access to the crowdtangle dashboard, only the token.** We do not have control over the accounts on each list (we don't know if an account is deleted or added from a list). This is because the addition of new accounts or deletion of accounts to lists is a sensitive issue and is only allowed by a specific team that cannot constantly inform us of changes to the lists.

**Comment by mattynoce** [comment]
Hey Matthew. Sounds like you came up with a solution, which is great. Though I'm curious why you have access to the API but not to the dashboard that's backing it. If you'd like to talk about it, write in to support@crowdtangle.com and we can get things sorted out.
