### ISSUE TITLE
/posts endpoint not returning posts from Saved Search

### ISSUE THREAD

**Issue by harshilshah4251** [CrowdTangle/API#20]
Hello,

We noticed that the posts from saved search are not being returned when we make a call to  https://api.crowdtangle.com/posts endpoint with start and end time. Crowdtangle's expected behavior should return posts from lists and saved searches when no listIds are provided however, Crowdtangle only returns posts from Lists. 

Could please look into this issue?

Also, is it possible to add list id information to each post that is being returned. Saved searches don't have accounts associated to it, so its not possible to map a post to Saved Search as of now. This is very critical for us because we would like to know if the post is coming from a list or a saved search.

Thank you,
Harshil.

**Comment by tkamin** [comment]
Hi Harshil,

Yep, something doesn't look right. We'll look into it.

Thanks,
Todd

**Comment by tkamin** [comment]
Hi Harshil,

What I saw appears to have been fixed. However, the /posts endpoint will only return results from lists, not from saved searches. You can get the results for a saved search in your dashboard by using the listIds parameter. I have updated the documentation to clarify this.

Todd
