### ISSUE TITLE
Including List ID in the returned post

### ISSUE THREAD

**Issue by harshilshah4251** [CrowdTangle/API#21]
Hello,

We need to know what List a post is coming from for our project. Until now, we were using the account ID to map a post to the List. But we noticed a problem with that approach.

For saved searches, there is no account ID associated to a post. If I have 10 saved searches and I make an API request to get posts from all of those 10 saved searches at once (comma-separated list ID endpoint), is there any way I can tell which Saved Search exactly the post is coming from?

Including List ID with the returned post will be extremely helpful for us.

Thank you so much,
Harshil.

**Comment by tkamin** [comment]
Hi Harshil,

Thanks for the suggestion. We will add it to our list of potential future improvements. For now though, I think you will need to make individual requests for each saved search. Please contact our support if you need increased rate limits to do this: https://help.crowdtangle.com/en/articles/3430410-faq-support-operations 

Regards,
Todd

cc: @dereksilverman, @georgemayer, @nshiffman
