### ISSUE TITLE
API returns truncated message

### ISSUE THREAD

**Issue by borch84** [CrowdTangle/API#22]
I am getting the '(truncated)' word at the end of a message returned in a post. Is there a way to get the full length of a message? The message is string with size of 4998bytes.  
Thanks.

**Comment by tkamin** [comment]
Hi,

No, unfortunately, we don't have a way to return message text over 5000 bytes. We note this limit in https://help.crowdtangle.com/en/articles/3323105-academics-researchers-faq for CSV downloads. The API has the same limit.

We have talked about increasing this limit, but it's not on any of our roadmaps right now.

Regards,
Todd

cc: @dereksilverman, @georgemayer, @mattynoce
