### ISSUE TITLE
Correct usage of searchTerm

### ISSUE THREAD

**Issue by borch84** [CrowdTangle/API#23]
Hi, what is the correct syntaxis for using the endpoint https://api.crowdtangle.com/posts/search ? 

I was checking the documentation https://github.com/CrowdTangle/API/wiki/Search but it is not clear to me how to search for an specific account. Do you have examples with curl command? Thanks.

**Comment by tkamin** [comment]
Hi,

CrowdTangle accountIds can be specified using inAccountIds by appending "inAccountIds=1" or "inAccountIds=1,2,3,4" to your URL.

CrowdTangle accountIds can be found using these API endpoints:

https://github.com/CrowdTangle/API/wiki/lists
and then 
https://github.com/CrowdTangle/API/wiki/List-Accounts

Hope this helps!
Todd

**Comment by borch84** [comment]
Hi Todd, thank you for your answer.
I run another test with this URL:
GET https://api.crowdtangle.com/posts/search?searchTerm=276464673186244&inAccountIds=276464673186244

I received this response from the API: 

{
    "status": 400,
    "code": 21,
    "message": "The 'inAccountIds' parameter must be a comma separated value of integers. Value received: 276464673186244,."
}

Do you know what is incorrect with the API call? 

Thanks.

**Comment by tkamin** [comment]
Hi,

Right, that's a Facebook page id. Unfortunately, the endpoint currently accepts CrowdTangle account IDs. In this case, the CrowdTangle id is 12785202, please try that out. 

GET https://api.crowdtangle.com/posts/search?searchTerm=rainbow&inAccountIds=12785202

There are 2 methods to find the CrowdTangle account ID right now: 

1) If the page is in your CrowdTangle dashboard, you can use the method in my previous answer to find the CrowdTangle ID. If not, unfortunately, it must be manually added to your dashboard first.

2) If you have a full post id from the page, you can get the CrowdTangle account Id via this endpoint: https://github.com/CrowdTangle/API/wiki/Posts#get-postid

Regards,
Todd

**Comment by borch84** [comment]
Thanks for your answer Todd. I executed again the request and this time I got:

{
    "status": 400,
    "code": 41,
    "message": "This request is not allowed with this token"
}

Now I guess this is a matter of permissions.

Thanks again!

**Comment by tkamin** [comment]
Ah, great, please contact support for access: https://help.crowdtangle.com/en/articles/3430410-faq-support-operations

**Comment by tkamin** [comment]
I just wanted to note that we've just added the ability to use platform-specific account IDs as filters in the API for the /posts and /posts/search endpoints. Please see the "accounts" parameter on https://github.com/CrowdTangle/API/wiki/Posts and https://github.com/CrowdTangle/API/wiki/Search.
