### ISSUE TITLE
inAccountIds parameter incorrect value

### ISSUE THREAD

**Issue by borch84** [CrowdTangle/API#24]
Hi, I would like to know the correct way to call the posts/search endpoint. 
If I run this call:
GET https://api.crowdtangle.com/posts/search?searchTerm=276464673186244&inAccountIds=276464673186244

I received this response from the API:

{
"status": 400,
"code": 21,
"message": "The 'inAccountIds' parameter must be a comma separated value of integers. Value received: 276464673186244,."
}

Do you know what is incorrect with the API call?

I am trying to find all the post messages from this account ID: 276464673186244

Thanks.

**Comment by tkamin** [comment]
I left an answer at https://github.com/CrowdTangle/API/issues/23 as it references my previous answer there.
