### ISSUE TITLE
Resolving platform-specific account IDs to CrowdTangle account IDs

### ISSUE THREAD

**Issue by chrisji** [CrowdTangle/API#25]
Hi there,

Do you have any exposed functionality for resolving platform-specific account IDs to CrowdTangle account IDs? Or is this something that must be performed manually via the dashboard? 

I can't see any endpoint for this, nor can I think of a robust work-around. Any advice greatly appreciated!

Many thanks

**Comment by tkamin** [comment]
Hi,

We've just added the ability to use platform-specific account IDs as filters in the API for the /posts and /posts/search endpoints. Please see the "accounts" parameter on https://github.com/CrowdTangle/API/wiki/Posts and https://github.com/CrowdTangle/API/wiki/Search (note, I think this one applies to the whole platform, not just the list or dashboard). Does this help solve your use case?

Thanks,
Todd

**Comment by tkamin** [comment]
And to answer your question, to get the CrowdTangle account ID, here are the current methods:

1) If the page is in your CrowdTangle dashboard, CrowdTangle account IDs can be found using these API endpoints:

https://github.com/CrowdTangle/API/wiki/lists
and then
https://github.com/CrowdTangle/API/wiki/List-Accounts

2) If you have a full post id, you can get the CrowdTangle account Id via this endpoint: https://github.com/CrowdTangle/API/wiki/Posts#get-postid

**Comment by chrisji** [comment]
Hi Todd,

Many thanks for the info - I think the full-platform `/search` endpoint will now handle what's needed!

If I understand correctly, I think all other methods will still require manual interaction with the dashboard.

Cheers,
Chris

**Comment by tkamin** [comment]
Hi Chris,

That's great news! That sounds right, /posts automatically limits to your dashboard.

Todd
