### ISSUE TITLE
Reddit is unsupported in links endpoint 

### ISSUE THREAD

**Issue by iosonosempreio** [CrowdTangle/API#26]
Reddit is not supported as a platform even though stated differently in the documentation:

![Screenshot 2020-11-30 at 11 56 06](https://user-images.githubusercontent.com/7115395/100601584-0f53ca00-3303-11eb-8f8d-6180bdaddc7e.png)

API call: 
`````
https://api.crowdtangle.com/links?token=MY-API-KEY&platforms=reddit&count=1000&link=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3D5lGjSHy4TKE&sortBy=date
`````

API response:
`````
{"status":400,"code":41,"message":"This request is not allowed with this platform. Allowed platforms: (facebook|instagram)."}
`````

**Comment by tkamin** [comment]
Hi,

It looks like we may have a mistake in the documentation. Can you send in your token to support@crowdtangle.com and reference me (Todd Kamin)?

Thanks,
Todd

**Comment by tkamin** [comment]
I updated the documentation. Reddit is not available for the Academics vertical. Thanks for opening the ticket, and my apologizes for the confusion.
