### ISSUE TITLE
Incorrect country code list on "Account" Wiki's description

### ISSUE THREAD

**Issue by lgelape** [CrowdTangle/API#27]
Hi,

I was checking the `Account` object [Wiki's page](https://github.com/CrowdTangle/API/wiki/Account) and it seems that the description of the `pageAdminTopCountry` column is not correct. It's description states that it corresponds to "The ISO country code of the the country from where the plurality of page administrators operate", linking the ISO country code [to this Wikipedia article](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes).

However, by using the data it seems that this is not the correct table - for example, there's no `"US"` on the ISO 639-1. It seems to me that the country codes which are being used are the [ISO 3166](https://en.wikipedia.org/wiki/List_of_ISO_3166_country_codes).

Thank you!

**Comment by tkamin** [comment]
Thank you! I have fixed the link on the Account page to match the link on https://github.com/CrowdTangle/API/wiki/Posts.
