### ISSUE TITLE
posts outside of date range for links endpoint

### ISSUE THREAD

**Issue by andehr** [CrowdTangle/API#28]
Hi CrowdTangle,

I was hoping you could help with an issue I've been having with the links API. I'm sending a query like following (newlines & unencoded dates for readability):

```
https://api.crowdtangle.com/links?
sortBy=date
&platforms=facebook
&count=500
&startDate=2020-12-18 11:25:50
&endDate=2020-12-18 16:21:43
&link=facebook.com%2Fphoto.php%3Ffbid%3D10159158681849108%2526set%3Dp.10159158681849108%2526type%3D3
```

The unencoded link query looks like this:  `facebook.com/photo.php?fbid=10159158681849108%26set=p.10159158681849108%26type=3`

If I get 500 posts back, I then set the end date to the oldest post in the response and query again to get the next 500.

But I'm getting stuck in a loop because I'm getting posts back outside of that date range, for example, the following poast has a date `2020-12-18 16:21:49` which is beyond the specified date range:

```
{
  "platformId": "1012988795858166",
  "platform": "Facebook",
  "date": "2020-12-18 16:21:49",
  "updated": "2020-12-18 16:28:03",
  "type": "photo",
  "message": "اخبريها... أيها العجوز أنها مسألة وقت فقط اخبريها...أن دوام الحال من المحال اخبريها...أن القصير والطويل لايطيل العمر اخبريها...أن مهما بلغ من جمالك سيذبل مع الأيام اخبريها...أن الجمال الأخلاق اخبريها...أن الرجل ينظر إليكي نظره شهوة لا نظرة امتلاك اخبريها...الرجل إذا نؤي الحلال فانتي ليسى في قائمة الأمهات اخبريها إذا كان تاج الملوك من ذهب فتاج المرآه الحياه والأدب....",
  "expandedLinks": [
    {
      "original": "https://www.facebook.com/photo.php?fbid=2733800783547614&set=gm.1012988795858166&type=3",
      "expanded": "https://www.facebook.com/photo.php?fbid=2733800783547614&set=gm.1012988795858166&type=3"
    }
  ],
  "link": "https://www.facebook.com/photo.php?fbid=2733800783547614&set=gm.1012988795858166&type=3",
  "postUrl": "https://www.facebook.com/groups/843186079505106/permalink/1012988795858166",
  "subscriberCount": 126761,
  "score": 0.8947368421052632,
  "media": [...],
  "statistics": {...},
  "account": {...},
  "legacyId": 0,
  "id": "13200471|1012988795858166"
}
```

Weirdly, after a fairly large number of retries, it seems to stop happening for a while, I then get posts in the proper range, and can resume pagination via date range - but only after having made repeated requests for duplicate data because it couldn't move the date range.

**Comment by tkamin** [comment]
Hi, 

I'll try to take a look at this next week. Some thoughts in the meantime:

1) We might be stripping the query string for this query when we do the search. In this example, searching for the id in the query string might be better: 10159158681849108 

sortBy=date&platforms=facebook&count=500&link=10159158681849108&searchField=INCLUDE_QUERY_STRINGS

2) We are constantly updating posts. To fulfill a /links query (or any really), we first filter and then fetch and build the full post data. My guess is that sometimes posts are updated between these phases and "date" is getting updated.

3) In your example, the post is after your end date, but that shouldn't affect your pagination unless there are 500 posts after the end date.

For example, if the posts returned have dates of :

2020-12-18 16:21:49
2020-12-18 16:21:44
2020-12-18 16:21:43 <- end date
... (496 posts)
2020-12-18 16:19:00

The next request would be 

&endDate=2020-12-18T116:19:00

4) It probably would be best to use "T" in there as that is how we document it.

5) /links supports a count up to 1000, and I recommended using the full 1000 for pagination like you are describing.

Todd

**Comment by andehr** [comment]
Hi Todd,

Thank you for your assistance!

I'll update my datetime format and increase count to 1000. 

On point 3, I'm always sorting by date, and taking the earliest date, so when this error presents itself, I believe I'm getting 500 posts that are all just after my endDate (so all outside the date range).

Best,
Andrew

**Comment by andehr** [comment]
Hi @tkamin 

I can confirm that even with count = 1000, and using the date format with the "T" as suggested, I can still produce the bug.

The easiest way I've found to consistently reproduce the bug is to make a query that would return tonnes of data, e.g. search for "the". Bearing in mind that this error happens with reasonable link queries too, just more rarely. E.g. (url decoded for readability):

```javascript
https://api.crowdtangle.com/links?
  count=1000&offset=0&
  startDate=2021-01-20T07:18:24&
  endDate=2021-01-20T12:18:24&
  sortBy=date&
  link=the&
  platforms=facebook
```

This usually returns a first 1000 results as expected, then I take the date on the oldest post in the response (as you describe above) which in this case was `2021-01-20T12:11:49` and set this as the new `endDate` parameter in the next query, in order to collect the next 1000.

After doing this 1-3 times, the bug normally arises.

When that happens, I get a batch of data back, where *all* posts are after my endDate, and in every time the error has happened, it has been exactly the previous batch, so my new query ends up being exactly the same as the last request over and over again. The wrong batch keeps being returned despite repeated attempts. For some queries, after many minutes of attempts, sometimes eventually the correct batch comes through and the process repeats again.

You can confirm when the error is happening, by checking that the oldest post in a response has a date field value equal to the `endDate` in the query that produced it.

**Comment by tkamin** [comment]
Hi Andrew, sorry for the delay. I believe we fixed this late Thursday 6/17/2021. Definitely let us know if you continue to see problems!

**Comment by andehr** [comment]
@tkamin thanks a lot, everything seems to be working for me so far!
