### ISSUE TITLE
Links endpoint: Twitter shares are missing `statistics` properties

### ISSUE THREAD

**Issue by RyanGladstone** [CrowdTangle/API#3]
I requested links (https://api.crowdtangle.com/links) info for this article:

https://www.washingtonpost.com/news/post-politics/wp/2017/08/17/trump-mourns-loss-of-beautiful-statues-and-monuments-in-wake-of-charlottesville-rally-over-robert-e-lee-statue/?hpid=hp_hp-top-table-main_monuments-950am%3Ahomepage%2Fstory&utm_term=.f07faf2daddf

In the list of results, Facebook posts had a properly filled-out statistics property, but Twitter entries had empty values:

```
 "statistics": {
          "actual": {
            
          },
          "expected": {
            
          }
}
```

**Comment by mattynoce** [comment]
Hi Ryan. That's not an error, actually, it's in accordance with Twitter's API terms of service. See here:

https://dev.twitter.com/overview/terms/policy

Obviously the exact text of this may change, so what's on the site is what's official, but I'm attaching what it says today solely for clarification, as it will likely remain clarifying even if the exact text changes:

```
If you provide Content to third parties, including downloadable datasets of Content or an API that returns Content, you will only distribute or allow download of Tweet IDs, Direct Message IDs, and/or User IDs.
```

So we cannot return any data outside of the IDs. I hope that helps.

**Comment by RyanGladstone** [comment]
Hi Matt 

Thanks for clarification.

Ryan
