### ISSUE TITLE
Account Page Category Types

### ISSUE THREAD

**Issue by timroty** [CrowdTangle/API#34]
On the [Account Object Wiki Page](https://github.com/CrowdTangle/API/wiki/Account), the pageCategory property states that all the page categories can be found at the link https://github.com/CrowdTangle/API/wiki/www.facebook.com/pages/category/. However, clicking the link redirects me to the main API wiki page. Is this intended behavior or is there another location I can find all the page categories?

**Comment by tkamin** [comment]
Thanks! I have fixed the link to point to https://www.facebook.com/pages/category/
