### ISSUE TITLE
Pagination.nextPage is not URL encoded

### ISSUE THREAD

**Issue by fabiogiglietto** [CrowdTangle/API#37]
Dear All,
I'm using the link endpoint to get shares for this URL: http://refpa.top/L?tag=49551727409&site=495517&ad=27409. The query returns more than 1000 results and I'd like to use nextpage value to iterate.

However, the nextpage value returned by
https://api.crowdtangle.com/links?link=http%3A%2F%2Frefpa.top%2FL%3Ftag%3D49551727409%26site%3D495517%26ad%3D27409&platforms=facebook,instagram&startDate=2021-04-12&endDate=2021-04-19&includeSummary=FALSE&includeHistory=FALSE&sortBy=date&searchField=TEXT_FIELDS_AND_IMAGE_TEXT&token=**ADDYOURTOKENHERE**&count=1000 is
https://api.crowdtangle.com/links?token=**ADDYOURTOKENHERE**&sortBy=date&endDate=2021-04-13T14:14:32&startDate=2021-04-12&platforms=facebook,instagram&link=http://refpa.top/L?tag=49551727409&site=495517&ad=27409&searchField=TEXT_FIELDS_AND_IMAGE_TEXT&count=1000 which returns an HTTP 400 because the link is not encoded.

I think it's a bug with this specific type of URLs that you may want to investigate.

**Comment by tkamin** [comment]
Thanks for the report, I'll look into it.

**Comment by tkamin** [comment]
This should be fixed! Please re-open if you still see problems. Thank you!
