### ISSUE TITLE
Score Calculation 

### ISSUE THREAD

**Issue by satsaras** [CrowdTangle/API#39]
When we pull data for articles thru api, there is a score associated with every article. How this score is getting created?

**Comment by sudharsan123** [comment]
@satsaras The score represents the overperforming/underperforming score if the `sortBy` param is `overperforming`/`underperforming` or the interaction rate if the `sortBy` param is `interaction_rate`. 

These help center articles go in depth on how these scores are calculated:
1. Overperforming - https://help.crowdtangle.com/en/articles/2013937-how-do-you-calculate-overperforming-scores
2. Interaction Rates - https://help.crowdtangle.com/en/articles/1141064-how-is-interaction-rate-calculated
