### ISSUE TITLE
Missing fields in API output

### ISSUE THREAD

**Issue by fabiogiglietto** [CrowdTangle/API#41]
Dear All,
it seems that the [account.* fields](https://github.com/CrowdTangle/API/wiki/Account) returned by the API suddenly changed. Missing fields are: handle, pageAdminTopCountry, pageDescription and pageCreatedDate.

Can you please check? Thank you in advance. Best, Fabio

**Comment by sudharsan123** [comment]
Could you provide a sample API query where these fields are missing? I'm not able to reproduce this issue from my side.

**Comment by fabiogiglietto** [comment]
Hi. I tried just now and it seems that it was a temporary issue as now all the fields seem to be there.
