### ISSUE TITLE
How to enable "Search Within Paths" in the link checker

### ISSUE THREAD

**Issue by maclemama** [CrowdTangle/API#7]
Hi CrowdTangle!

In the link checker inside crowdtangle website "https://apps.crowdtangle.com/" there is an option  "Search Within Paths" which would search link from the post path not the copy of the post.

I am wondering if this is an option in the API too?

If not, I would suggest this to be included in your future API update, because many people share website link without placing the link inside the copy. With this option enabled,  end user can truly get the complete view of the link sharing activities.

Thank you!!

**Comment by mattynoce** [comment]
Hi maclemama. Thanks for the note -- you're totally right that this should be in the API. I don't have a timeframe for you, but this is something we'll look into and try to get on the roadmap.
